### ISSUE TITLE
php artisan migrate --path="vendor/rinvex/attributable/database/migrations" ERROR!!

### ISSUE THREAD

**Issue by Deepseath** [rinvex/laravel-attributes#10]
run 

> php artisan migrate --path="vendor/rinvex/attributable/database/migrations"

show error:

>   [Illuminate\Database\QueryException]
  SQLSTATE[42000]: Syntax error or access violation: 1103 Incorrect table name '' (SQL: create table `` (`id` int unsigned not null auto_increment primary key, `slug` varchar(255) not null, `name` json not null, `description` json null, `sort_order` mediumint unsigned not null default '0', `group` varchar(255) null, `type` varchar(255) not null, `is_required` tinyint(1) not null default '0', `is_collection` tinyint(1) not null default '0', `default` text null, `created_at` timestamp null, `updated_at` timestamp null) default character set utf8mb4 collate utf8mb4_general_ci)

>  [PDOException]
  SQLSTATE[42000]: Syntax error or access violation: 1103 Incorrect table name ''

Why? thk!!!

**Comment by biglazy** [comment]
run
`cp vendor/rinvex/attributable/config/config.php config/rinvex.attributable.php`
then it will be OK.

**Comment by biglazy** [comment]
run:
> cp vendor/rinvex/attributable/config/config.php config/rinvex.attributable.php

If in laravel, it would be OK here. 
If in lumen, this config file must be loaded:
> config/rinvex.attributable.php

**Comment by Omranic** [comment]
This issue should be fixed on current **develop** branch, use `composer require rinvex/attributes:dev-develop` to install the package. Please feel free to reopen this issue or a new issue, if you need further assistance :)
