### ISSUE TITLE
Attributes for specific Entity?

### ISSUE THREAD

**Issue by divdax** [rinvex/laravel-attributes#106]
How i can add attributes for a specific model/entity, in my case `ProductCategory`?
Not every product has the same attributes, so i want to bind certain attributes to a category and not all categories.

**Comment by Omranic** [comment]
That's the core of this package, but you need to understand how this package works first. You need to attach that attribute to the entity called `Category`, then you can assign that attribute to which category you want. Checkout the docs for more details: https://github.com/rinvex/laravel-attributes#manage-attribute-entities

Once you get your head around it, it will make sense and will feel easy and straightforward.
