### ISSUE TITLE
How do you interact with lumen & laravel?

### ISSUE THREAD

**Issue by lpw685** [rinvex/laravel-attributes#11]
I want to use it, but it's not good. There are a lot of bugs to lumen & laravel. please maintain and solve it, thanks!

**Comment by Omranic** [comment]
Thank you @lpw685 for your feedback, first sorry for the delay. Yes this package still not yet tagged as stable. You can only use develop branch for now, use: composer require rinvex/attributes:dev-develop if should work smoothly even it's still in development, let me know if you've any issues.

P.S. Not tested or intended to work with Lumen, but you can try it 😉
