### ISSUE TITLE
 (1/1) MassAssignmentException  content

### ISSUE THREAD

**Issue by nirbhay94** [rinvex/laravel-attributes#12]
On running
        $value = new Varchar(['content' => 'Alexandria', 'attribute_id' => 1, 'entity_type' => 'App\Company', 'entity_id' => 1]);

Mass Assignment error shows up
How to assign attribute to entity and push value?

**Comment by Omranic** [comment]
Should be fixed now, note that this package still not yet tagged as stable. You must only use develop branch for now, use: `composer require rinvex/attributes:dev-develop` it should work smoothly even it's still in development.

- You can assign attribute to an entity like this example:
https://github.com/rinvex/attributes#add-eav-to-eloquent-model
- And you can assign values as you normally do with eloquent!
https://github.com/rinvex/attributes/blob/develop/README.md#assigning-values

Please feel free to reopen this issue or a new issue, if you need further assistance :)
