### ISSUE TITLE
Why don't you support php 7.3

### ISSUE THREAD

**Issue by kimtrien** [rinvex/laravel-attributes#120]
This is a great package.

But why don't you support php 7.3

I have just updated Laravel to version 7.8.1 and run it on php 7.3.17 

Now I cannot install your package.

**Comment by Omranic** [comment]
Hello @kjmtrue thank you for your question.
PHP v7.3 already supported on an older release of this package v3.x

The new release v4.x already supports Laravel v7.x, but also requires PHP v7.4 as a minimum requirement.

If you're still on an older version of PHP, feel free to fork this package and lower the PHP dependency, and it should work smoothly for you 👍
