### ISSUE TITLE
How do we create multi value attributes and custom type.

### ISSUE THREAD

**Issue by yasin7044** [rinvex/laravel-attributes#125]

**Comment by Omranic** [comment]
Thank you for your patience, your question is actually answered in the [docs](https://github.com/rinvex/laravel-attributes#introduction). I know it's long and not easy docs, but that's the nature of EAV anyway, you need to understand it well first before using it. Please refer to the docs.

Although, I did a complete rewrite for the whole package and changed how collections work. In the new refactor, it actually uses normal relationships, and should be easy and straightforward like default Laravel relationships. Although, that refactor is incomplete.

I'm still not happy with the overall performance (I believe we can reduce number of executed queries), if you want to check it out, see https://github.com/rinvex/laravel-attributes/tree/refactor-to-native-laravel-relationships

Currently no plans to merge that rewrite, but hopefully sometime I can get it to a stable state, improve performance and release it. Any help with that branch would be much appreciated! 🙂
