### ISSUE TITLE
Missing AttributableInterface

### ISSUE THREAD

**Issue by Miwi35** [rinvex/laravel-attributes#130]
Great module!
It would just have been great to have AttributableInterface that acts as a contract filled by the Attributable trait.
It would be useful to test if the Entity has additionnal attributes to generate form for example. Right now we are force to test if Entity uses the trait.

Additionnally, traits are just implementation of common behaviors while interface are descriptions of behavior, so it makes sense!

Keep up the good work!

**Comment by Omranic** [comment]
Thank you @Miwi35 for your feedback, I would be happy to look into it, if someone can submit a PR for that ;)
