### ISSUE TITLE
 illuminate/console ... but it conflicts with another require

### ISSUE THREAD

**Issue by DonBroughton** [rinvex/laravel-attributes#134]
While attempting to:
**composer require rinvex/laravel-attributes**
on a new project, I receive:

`Your requirements could not be resolved to an installable set of packages.

  Problem 1
    - Root composer.json requires rinvex/laravel-attributes ^4.1 -> satisfiable by rinvex/laravel-attributes[v4.1.0].
    - rinvex/laravel-attributes v4.1.0 requires illuminate/console ^7.0.0 -> found illuminate/console[v7.0.0, ..., 7.x-dev] but it conflicts with another require.`

I am unable to install the package in a new Laravel installation.

**Comment by Omranic** [comment]
Package is now updated to support PHP v8 (and v7.4 as well), Laravel v8, Composer v2.

Please check and let me know if you still have any issues.

**Comment by JoaquinVilchez** [comment]
> Package is now updated to support PHP v8 (and v7.4 as well), Laravel v8, Composer v2.
> 
> Please check and let me know if you still have any issues.

Hi, I can't fix this problem... I can't install the package.

My carasteristics are:
Laravel Framework 7.30.4
PHP 7.4.10
Composer version 2.0.8

You say that I have to update to laravel 8 and php 8?

Thank you.

**Comment by Omranic** [comment]
@JoaquinVilchez if you need to use latest version, then yes you need to upgrade to Laravel v8, but it's not required to upgrade your PHP version. Otherwise, check older versions that supports Laravel v7 or less (but in this case it doesn't support composer v2, only v1)..
