### ISSUE TITLE
Segmentation fault when load relationship after remove all cached data

### ISSUE THREAD

**Issue by donamkhanh** [rinvex/laravel-attributes#139]
Hi,

I'm using laravel-attributes version 2.1.1 (I have to use because our Laravel is 5.8). When we deploy new version, we deleted all cache folder (or move to new folder location which cache data are not exists). Everything work fines except loading attribute relationship, it throws segmentation fault.

What should I do in this case?

**Comment by donamkhanh** [comment]
After checking, I found the reason: attribute slug name is same with entity field then it causes segmentation fault.

**Comment by Omranic** [comment]
Glad your issue is now solved, don't hesitate to ask for help if you faced any further issues 👍
