### ISSUE TITLE
supporting Maria DB dynamic columns

### ISSUE THREAD

**Issue by pishguy** [rinvex/laravel-attributes#145]
this package supported MariaDb dynamic columns?

**Comment by Omranic** [comment]
This package uses column types that's supported by MySQL, MariaDB, and PostgreSQL.

If you've a specific use case in mind, please explain so we can help you better.

**Comment by pishguy** [comment]
in MariaDB as we know we have dynamic column and it's supported with maria-db which we have some sql command into that to select or make queries

**Comment by Omranic** [comment]
I understand, but you still didn't mention how this is related to the package, why do you need dynamic fields and what's your use case for it in this package?
