### ISSUE TITLE
jeremeamia/superclosure is abandoned

### ISSUE THREAD

**Issue by Yezper** [rinvex/laravel-attributes#153]
When installing laravel-attributes, composer gives the following warning:

```
Package jeremeamia/superclosure is abandoned, you should avoid using it. Use opis/closure instead.
```

Can this be done?

Best,
Jesper

**Comment by Omranic** [comment]
Thank you @Yezper, you can ignore that warning, it will still install without issues.

I did a complete rewrite for the whole package and removed that dependency, and simplified the code a lot, but I'm still not happy with the overall performance (I believe we can reduce number of executed queries), if you want to check it out, see https://github.com/rinvex/laravel-attributes/tree/refactor-to-native-laravel-relationships

Currently no plans to merge that rewrite, but hopefully sometime I can get it to a stable state, improve performance and release it.

Any help would be appreciated.
