### ISSUE TITLE
Translations for Value content

### ISSUE THREAD

**Issue by pcfjojo** [rinvex/laravel-attributes#157]
*Value field content* 
Is it possible to add HasTranslations for Value model?

Example:
` $category = Category::first();
        $category->size = array(
            "it" => "Grosso",
            "en" => "Big"
        );
        $category->save();`

something like this?

**Comment by Omranic** [comment]
Thank you @pcfjojo for the proposal, yes you can do that by overriding the `Value` model and utilize the trait, but I believe we'll need to make it easier to override the model from config options like other models, so it's just one change to the core package, and you can use your custom model https://github.com/rinvex/laravel-attributes/blob/master/config/config.php#L24-L29

I'd be happy to consider PRs..
