### ISSUE TITLE
Problems with traits HasTranslations and ValidatingTrait

### ISSUE THREAD

**Issue by alexanderpavlov** [rinvex/laravel-attributes#21]
The "Rinvex\Attributes\Models\Attribute" class has two traits:
Rinvex\Support\Traits\HasTranslations;
Rinvex\Support\Traits\ValidatingTrait

And these traits don't exists in the package... So I have an error when try to use it.

**Comment by Omranic** [comment]
Which branch you're using?

**Comment by alexanderpavlov** [comment]
I'm using master. I've installed it using the command "composer require rinvex/attributes"

**Comment by alexanderpavlov** [comment]
I tried to replace these traits with 
Spatie\Translatable\HasTranslations
Watson\Validating\ValidatingTrait 
but without success, because Watson\Validating\ValidatingTrait has no "validating" method :(

**Comment by brenjt** [comment]
I am having the same issue. Those traits do not exist. @alexanderpavlov a way to get around this is to overwrite the attribute model in the config like so:

```
return [
    'attributes' => [
        // ... tables

        // Attributes Models
        'models' => [
            'attribute' => \App\Domain\Attribute::class,
            'attribute_entity' => \Rinvex\Attributes\Models\AttributeEntity::class,
        ],
    ]
];
```
Then in your model change the boot method to listen for the validating event like so

```
/**
 * {@inheritdoc}
 */
protected static function boot()
{
    parent::boot();

    \Event::listen('eloquent.validating: ' . static::class, function (self $attribute) {
        if ($attribute->exists && $attribute->getSlugOptions()->generateSlugsOnUpdate) {
            $attribute->generateSlugOnUpdate();
        } elseif (! $attribute->exists && $attribute->getSlugOptions()->generateSlugsOnCreate) {
            $attribute->generateSlugOnCreate();
        }
    });
}
```

Also change the traits that are erroring out the floowing:
```
use Spatie\Translatable\HasTranslations;
use Watson\Validating\ValidatingTrait;
```

**Comment by brenjt** [comment]
@alexanderpavlov Nevermind, this solution works but only reveals more bugs. This package is far away from production.

**Comment by alexanderpavlov** [comment]
@brenjt thanks! I'll try it.

**Comment by Omranic** [comment]
@alexanderpavlov @brenjt sorry for the delay. These traits are available on the develop branch, and yes this package still not yet tagged as stable. You can only use develop branch for now, use: `composer require rinvex/attributes:dev-develop` it should work smoothly even it's still in development, let me know if you've any issues.

**Comment by Omranic** [comment]
Please feel free to reopen this issue or a new issue, if you need further assistance :)
