### ISSUE TITLE
Not available for laravel version 5.5

### ISSUE THREAD

**Issue by RushabhJoshi** [rinvex/laravel-attributes#25]
When I tried to install this package I got this message

Problem 1
    - Installation request for rinvex/attributes ^0.0.3 -> satisfiable by rinvex/attributes[v0.0.3].
    - rinvex/attributes v0.0.3 requires rinvex/cacheable dev-develop -> satisfiable by rinvex/cacheable[dev-develop] but these conflict with your requirements or minimum-stability.

Then I tried to install rinvex/cacheable I got this

Problem 1
    - Installation request for rinvex/cacheable ^0.0.2 -> satisfiable by rinvex/cacheable[v0.0.2].
    - Conclusion: remove laravel/framework v5.5.22
    - Conclusion: don't install laravel/framework v5.5.22
    - rinvex/cacheable v0.0.2 requires illuminate/database ~5.4.0 -> satisfiable by illuminate/database[v5.4.0, v5.4.13, v5.4.17, v5.4.19, v5.4.27, v5.4.36, v5.4.9].
    - don't install illuminate/database v5.4.0|don't install laravel/framework v5.5.22
    - don't install illuminate/database v5.4.13|don't install laravel/framework v5.5.22
    - don't install illuminate/database v5.4.17|don't install laravel/framework v5.5.22
    - don't install illuminate/database v5.4.19|don't install laravel/framework v5.5.22
    - don't install illuminate/database v5.4.27|don't install laravel/framework v5.5.22
    - don't install illuminate/database v5.4.36|don't install laravel/framework v5.5.22
    - don't install illuminate/database v5.4.9|don't install laravel/framework v5.5.22
    - Installation request for laravel/framework (locked at v5.5.22, required as 5.5.*) -> satisfiable by laravel/framework[v5.5.22].

**Comment by Omranic** [comment]
This package still not yet tagged as stable. You can only use **develop** branch for now, use: `composer require rinvex/attributes:dev-develop` it should work smoothly even it's still in development. Please feel free to reopen this issue or a new issue, if you need further assistance :)

**Comment by RushabhJoshi** [comment]
Thank you
