### ISSUE TITLE
EAV values empty

### ISSUE THREAD

**Issue by psychonetic** [rinvex/laravel-attributes#27]
If I create an entity and let's say we have a size attribute, the size is always null.
```
$art = Article::find(1);  //$art->size = null

$art = Article::with('eav)->get(); //size also empty

//in Model Article  protected $with = ['eav'];

$art = Article::all(); //size also empty
```

Is there anything wrong how I access the size or is this a bug?
The value in the database is correct. So in the database I can find the size value (it's "m").

Laravel 5.5, attributes Version is 0.0.3.

**Comment by Omranic** [comment]
This package still not yet tagged as stable. You can only use **develop** branch for now, use: `composer require rinvex/attributes:dev-develop` it should work smoothly even it's still in development. Please feel free to open a new issue or open this one, if you need further assistance :slightly_smiling_face:

P.S. there was some changes recently to this packag, so make sure to review the docs 🙂
