### ISSUE TITLE
Trait 'Rinvex\Support\Traits\HasTranslations' not found

### ISSUE THREAD

**Issue by tongkai-wzq** [rinvex/laravel-attributes#28]
D:\phpStudy\site\weyoung\vendor\rinvex\attributes\src\Models\Attribute.php

     * @method static \Illuminate\Database\Eloquent\Builder|\Rinvex\Attributes\Models\Attribute ordered($direction = 'asc')
     * @method static \Illuminate\Database\Eloquent\Builder|\Rinvex\Attributes\Models\Attribute whereCreatedAt($value)
     * @method static \Illuminate\Database\Eloquent\Builder|\Rinvex\Attributes\Models\Attribute whereDefault($value)
     * @method static \Illuminate\Database\Eloquent\Builder|\Rinvex\Attributes\Models\Attribute whereDescription($value)
     * @method static \Illuminate\Database\Eloquent\Builder|\Rinvex\Attributes\Models\Attribute whereGroup($value)
     * @method static \Illuminate\Database\Eloquent\Builder|\Rinvex\Attributes\Models\Attribute whereId($value)
     * @method static \Illuminate\Database\Eloquent\Builder|\Rinvex\Attributes\Models\Attribute whereIsCollection($value)
     * @method static \Illuminate\Database\Eloquent\Builder|\Rinvex\Attributes\Models\Attribute whereIsRequired($value)
     * @method static \Illuminate\Database\Eloquent\Builder|\Rinvex\Attributes\Models\Attribute whereName($value)
     * @method static \Illuminate\Database\Eloquent\Builder|\Rinvex\Attributes\Models\Attribute whereSlug($value)
     * @method static \Illuminate\Database\Eloquent\Builder|\Rinvex\Attributes\Models\Attribute whereSortOrder($value)
     * @method static \Illuminate\Database\Eloquent\Builder|\Rinvex\Attributes\Models\Attribute whereType($value)
     * @method static \Illuminate\Database\Eloquent\Builder|\Rinvex\Attributes\Models\Attribute whereUpdatedAt($value)
     * @mixin \Eloquent
     */
    class Attribute extends Model implements AttributeContract, Sortable
    {
        use HasSlug;
        use SortableTrait;
        use HasTranslations;
        use ValidatingTrait;
        use CacheableEloquent;
     
        /**
         * {@inheritdoc}
         */
        protected $fillable = [
            'name',
            'slug',
            'description',
            'sort_order',
            'group',
            'type',
            'entities',
            'is_required',
            'is_collection',
            'default',
        ];
     
        /**

Arguments

    "Trait 'Rinvex\Support\Traits\HasTranslations' not found"

**Comment by Omranic** [comment]
This is fixed in `dev-develop` branch, just in case anyone viewing this issue. For all untagged/unstable packages please use `dev-develop` branch for now as it's the most up to date.
