### ISSUE TITLE
Installation Failed On Laravel 5.2

### ISSUE THREAD

**Issue by chiragsenjaliya** [rinvex/laravel-attributes#29]
Hello,
I have used `composer require rinvex/cacheable dev-develop` but it won't install!

getting this error:

Problem 1
    - Installation request for rinvex/attributes dev-develop -> satisfiable by rinvex/attributes[dev-develop].
    - rinvex/attributes dev-develop requires rinvex/cacheable dev-develop -> satisfiable by rinvex/cacheable[dev-develop] but these conflict with your requirements or minimum-stability.

**Comment by Omranic** [comment]
Sorry, we don’t maintain old Laravel releases support. Laravel v5.5+ is required.

Also in regard to the above issue, you’ve to change your project’s minimum stability to *dev* since this package still in development and not tagged as stable yet.

**Comment by chiragsenjaliya** [comment]
Thank you.
