### ISSUE TITLE
installation failed

### ISSUE THREAD

**Issue by aliakel** [rinvex/laravel-attributes#3]
Updating dependencies (including require-dev)
Your requirements could not be resolved to an installable set of packages.

  Problem 1
    - Installation request for rinvex/attributable ^0.0.1 -> satisfiable by rinv
ex/attributable[v0.0.1].
    - rinvex/attributable v0.0.1 requires rinvex/cacheable dev-develop -> satisf
iable by rinvex/cacheable[dev-develop] but these conflict with your requirements
 or minimum-stability.

Installation failed, reverting ./composer.json to its original content.

**Comment by Deepseath** [comment]
me too ...

**Comment by nirbhay94** [comment]
Try this:
sudo composer require rinvex/cacheable dev-develop
and then 
sudo composer require rinvex/attributable

**Comment by Omranic** [comment]
@aliakel @Deepseath @Nirbhay94 Sorry for the delay, note that this package still not yet tagged as stable. You can only use develop branch for now, use: `composer require rinvex/attributes:dev-develop` it should work smoothly even it's still in development. Please feel free to reopen this issue or a new issue, if you need further assistance :)
