### ISSUE TITLE
Instalation fails on Laravel 5.5

### ISSUE THREAD

**Issue by RadoslavAngelov** [rinvex/laravel-attributes#34]
Hello, the following issue. My Laravel version is 5.5.36. When I try to require the package the output is:

 Problem 1
    - rinvex/attributes dev-develop requires rinvex/support dev-develop -> satisfiable by rinvex/support[dev-develop].
    - Installation request for rinvex/attributes dev-develop -> satisfiable by rinvex/attributes[dev-develop].
    - Conclusion: remove laravel/framework v5.5.36
    - Conclusion: don't install laravel/framework v5.5.36
    - rinvex/support dev-develop requires illuminate/validation ~5.6.0 -> satisfiable by laravel/framework[5.6.x-dev], illuminate/validation[5.6.x-dev, v5.6.0, v5.6.1, v5.6.2, v5.6.3, v5.6.4, v5.6.5, v5.6.6, v5.6.7, v5.6.8, v5.6.9].
    - laravel/framework 5.6.x-dev conflicts with laravel/framework[v5.5.36].
    - don't install illuminate/validation 5.6.x-dev|don't install laravel/framework v5.5.36
    - don't install illuminate/validation v5.6.0|don't install laravel/framework v5.5.36
    - don't install illuminate/validation v5.6.1|don't install laravel/framework v5.5.36
    - don't install illuminate/validation v5.6.2|don't install laravel/framework v5.5.36
    - don't install illuminate/validation v5.6.3|don't install laravel/framework v5.5.36
    - don't install illuminate/validation v5.6.4|don't install laravel/framework v5.5.36
    - don't install illuminate/validation v5.6.5|don't install laravel/framework v5.5.36
    - don't install illuminate/validation v5.6.6|don't install laravel/framework v5.5.36
    - don't install illuminate/validation v5.6.7|don't install laravel/framework v5.5.36
    - don't install illuminate/validation v5.6.8|don't install laravel/framework v5.5.36
    - don't install illuminate/validation v5.6.9|don't install laravel/framework v5.5.36
    - Installation request for laravel/framework (locked at v5.5.36, required as 5.5.*) -> satisfiable by laravel/framework[v5.5.36].

I have tried two require the dev-develop version but there is no change. Is the package available for this version of Laravel?

**Comment by IsraelOrtuno** [comment]
The package requires 5.6 in the main branches. You will have to require `0.0.3` to make it work with 5.5.

**Comment by benyanke** [comment]
Is there an option for 5.4?

**Comment by RadoslavAngelov** [comment]
I have tried to require all versions till 0.0.1 but I get the following errors:

**composer require rinvex/attributes:0.0.3**

` Problem 1
    - rinvex/attributes v0.0.3 requires rinvex/cacheable dev-develop -> satisfiable by rinvex/cacheable[dev-develop].
    - Installation request for rinvex/attributes 0.0.3 -> satisfiable by rinvex/attributes[v0.0.3].
    - Conclusion: remove laravel/framework v5.5.36
    - Conclusion: don't install laravel/framework v5.5.36
    - rinvex/cacheable dev-develop requires illuminate/database ~5.6.0 -> satisfiable by laravel/framework[5.6.x-dev], illuminate/database[5.6.x-dev, v5.6.0, v5.6.1, v5.6.2, v5.6.3, v5.6.4, v5.6.5, v5.6.6, v5.6.7, v5.6.8, v5.6.9].
    - laravel/framework 5.6.x-dev conflicts with laravel/framework[v5.5.36].
    - don't install illuminate/database 5.6.x-dev|don't install laravel/framework v5.5.36
    - don't install illuminate/database v5.6.0|don't install laravel/framework v5.5.36
    - don't install illuminate/database v5.6.1|don't install laravel/framework v5.5.36
    - don't install illuminate/database v5.6.2|don't install laravel/framework v5.5.36
    - don't install illuminate/database v5.6.3|don't install laravel/framework v5.5.36
    - don't install illuminate/database v5.6.4|don't install laravel/framework v5.5.36
    - don't install illuminate/database v5.6.5|don't install laravel/framework v5.5.36
    - don't install illuminate/database v5.6.6|don't install laravel/framework v5.5.36
    - don't install illuminate/database v5.6.7|don't install laravel/framework v5.5.36
    - don't install illuminate/database v5.6.8|don't install laravel/framework v5.5.36
    - don't install illuminate/database v5.6.9|don't install laravel/framework v5.5.36
    - Installation request for laravel/framework (locked at v5.5.36, required as 5.5.*) -> satisfiable by laravel/framework[v5.5.36].`

**composer require rinvex/attributes:0.0.2**

` Problem 1
    - rinvex/attributes v0.0.2 requires rinvex/cacheable dev-develop -> satisfiable by rinvex/cacheable[dev-develop].
    - Installation request for rinvex/attributes 0.0.2 -> satisfiable by rinvex/attributes[v0.0.2].
    - Conclusion: remove laravel/framework v5.5.36
    - Conclusion: don't install laravel/framework v5.5.36
    - rinvex/cacheable dev-develop requires illuminate/database ~5.6.0 -> satisfiable by laravel/framework[5.6.x-dev], illuminate/database[5.6.x-dev, v5.6.0, v5.6.1, v5.6.2, v5.6.3, v5.6.4, v5.6.5, v5.6.6, v5.6.7, v5.6.8, v5.6.9].
    - laravel/framework 5.6.x-dev conflicts with laravel/framework[v5.5.36].
    - don't install illuminate/database 5.6.x-dev|don't install laravel/framework v5.5.36
    - don't install illuminate/database v5.6.0|don't install laravel/framework v5.5.36
    - don't install illuminate/database v5.6.1|don't install laravel/framework v5.5.36
    - don't install illuminate/database v5.6.2|don't install laravel/framework v5.5.36
    - don't install illuminate/database v5.6.3|don't install laravel/framework v5.5.36
    - don't install illuminate/database v5.6.4|don't install laravel/framework v5.5.36
    - don't install illuminate/database v5.6.5|don't install laravel/framework v5.5.36
    - don't install illuminate/database v5.6.6|don't install laravel/framework v5.5.36
    - don't install illuminate/database v5.6.7|don't install laravel/framework v5.5.36
    - don't install illuminate/database v5.6.8|don't install laravel/framework v5.5.36
    - don't install illuminate/database v5.6.9|don't install laravel/framework v5.5.36
    - Installation request for laravel/framework (locked at v5.5.36, required as 5.5.*) -> satisfiable by laravel/framework[v5.5.36].
`

**composer require rinvex/attributes:0.0.1**

` Problem 1
    - rinvex/attributes v0.0.1 requires rinvex/cacheable dev-develop -> satisfiable by rinvex/cacheable[dev-develop].
    - Installation request for rinvex/attributes 0.0.1 -> satisfiable by rinvex/attributes[v0.0.1].
    - Conclusion: remove laravel/framework v5.5.36
    - Conclusion: don't install laravel/framework v5.5.36
    - rinvex/cacheable dev-develop requires illuminate/database ~5.6.0 -> satisfiable by laravel/framework[5.6.x-dev], illuminate/database[5.6.x-dev, v5.6.0, v5.6.1, v5.6.2, v5.6.3, v5.6.4, v5.6.5, v5.6.6, v5.6.7, v5.6.8, v5.6.9].
    - laravel/framework 5.6.x-dev conflicts with laravel/framework[v5.5.36].
    - don't install illuminate/database 5.6.x-dev|don't install laravel/framework v5.5.36
    - don't install illuminate/database v5.6.0|don't install laravel/framework v5.5.36
    - don't install illuminate/database v5.6.1|don't install laravel/framework v5.5.36
    - don't install illuminate/database v5.6.2|don't install laravel/framework v5.5.36
    - don't install illuminate/database v5.6.3|don't install laravel/framework v5.5.36
    - don't install illuminate/database v5.6.4|don't install laravel/framework v5.5.36
    - don't install illuminate/database v5.6.5|don't install laravel/framework v5.5.36
    - don't install illuminate/database v5.6.6|don't install laravel/framework v5.5.36
    - don't install illuminate/database v5.6.7|don't install laravel/framework v5.5.36
    - don't install illuminate/database v5.6.8|don't install laravel/framework v5.5.36
    - don't install illuminate/database v5.6.9|don't install laravel/framework v5.5.36
    - Installation request for laravel/framework (locked at v5.5.36, required as 5.5.*) -> satisfiable by laravel/framework[v5.5.36].`

**Comment by RadoslavAngelov** [comment]
I think the reason for the issue is that all versions of the package require rinvex/cacheble dev-develop and since the dev-develop version of rinvex/cacheble recently has been changed from 0.0.2 to 0.0.3 and the 0.0.3 version requires illuminate/database 5.6.

**Comment by Omranic** [comment]
Sorry, we don’t maintain old Laravel releases support. Laravel v5.6+ is required.

Also note that you’ve to change your project’s minimum stability to *dev* since this package still not tagged as stable yet.
