### ISSUE TITLE
Method Illuminate\Support\Collection::add does not exist. 

### ISSUE THREAD

**Issue by mepoohsta** [rinvex/laravel-attributes#38]
I don't know exactly what I need to do. 

I want to add multiple values to attr.
Trying this.

``$model->tags->add(['Alexandria', 'Cairo'])``

I added this code to my Model

``    /**
     * Create a new Eloquent Collection instance.
     *
     * @param  array  $models
     * @return Rinvex\Attributes\Support\ValueCollection
     */
    public function newCollection(array $models = [])
    {
        return new ValueCollection($models);
    }``

Get this 
![image](https://user-images.githubusercontent.com/9480365/39099567-b3da39a0-4685-11e8-9dd7-6889ff4bf3db.png)

**Comment by IsraelOrtuno** [comment]
Not sure right now. I would need to have the same state in the database to try to reproduce the issue.

**Comment by mepoohsta** [comment]
It was not in the database, some method was returned not the ValueCollection() but the Collection().

**Comment by Omranic** [comment]
@mepoohsta thank you for reaching out, and sorry for the delay!
Well, buddy there's no `add` method in Laravel's Collections! And`ValueCollection` actually inherits from it, so you just need to use `push` like normal, make sure to *[READ THE WHOLE DOCUMENTATION](https://github.com/rinvex/attributes/tree/develop#rinvexattributessupportvaluecollection)* as it's really mandatory to understand how this package works. And you can visit official [Laravel Collections](https://laravel.com/docs/5.6/collections#method-push) page too 🙂 

P.S. If you're using this package for managing tags, it's not efficient and highly not recommended. You can use [Rinvex Tags](https://github.com/rinvex/tags) instead.
