### ISSUE TITLE
How to store money values?

### ISSUE THREAD

**Issue by mepoohsta** [rinvex/laravel-attributes#39]
Something like this

Value + currency

![image](https://user-images.githubusercontent.com/9480365/39351955-de19d390-4a0b-11e8-9511-ecc27f5bc24c.png)

**Comment by IsraelOrtuno** [comment]
As of now I think you need two attributes for that:
- Value
- Currency

How would you do with a normal database schema? Probably two columns, right?

**Comment by mepoohsta** [comment]
But how to store multiple money-currency values in one model? If I store multiple money values, how to bind one money to currency and another money to another currency? Maybe you can help.

**Comment by IsraelOrtuno** [comment]
Create your migration for storing that value type:
https://github.com/rinvex/attributes/blob/master/database/migrations/2017_01_19_040622_create_attribute_integer_values_table.php

Create the model for that value:
https://github.com/rinvex/attributes/blob/master/src/Models/Type/Integer.php

Add it to map:
https://github.com/rinvex/attributes/blob/master/src/Providers/AttributesServiceProvider.php#L57-L63

This should work :)
