### ISSUE TITLE
Error when saving an empty string

### ISSUE THREAD

**Issue by ya-tmch** [rinvex/laravel-attributes#41]
```
$model->varcharField = "";
$model->save()
```

<img width="635" alt="2018-05-12 23 48 58" src="https://user-images.githubusercontent.com/6257517/39957472-43fff222-563f-11e8-8e50-b383c29de91e.png">

P.S. How save a null in the field value??

**Comment by IsraelOrtuno** [comment]
`required` rule does not pass if "". Add `nullable` to your rule.
