### ISSUE TITLE
Why drop 5.5 LTS while 5.6 has no LTS

### ISSUE THREAD

**Issue by mikebranderhorst** [rinvex/laravel-attributes#42]

**Comment by Omranic** [comment]
As this package still under development, and it's not tagged as stable yet, our strategy is to always support latest versions of both PHP and Laravel, for many reasons, but once the package is tagged as stable, you'll be able to use tagged releases that's compatible with your own software. Even for now, you can look back when we dropped that support, and lock your package installation to that commit, but you won't be able to update the package at this point. Hope this make sense, if not then sorry for the inconvenience :)
