### ISSUE TITLE
I can't run php artisan rinvex:migrate:attributes

### ISSUE THREAD

**Issue by mvn-trungtran-dn** [rinvex/laravel-attributes#48]
Hi guys !
I can't run php artisan rinvex:migrate:attributes. it do not work
`run: php artisan rinvex:migrate:attributes`
 i got an errror: 
  ``` There are no commands defined in the "rinvex:migrate" namespace.```
Anybody can help me?

**Comment by IsraelOrtuno** [comment]
Actually the command is `rinvex:attributes:migrate`

**Comment by IsraelOrtuno** [comment]
I have just tested both, mismatch between branches.

**Comment by Omranic** [comment]
Merged `develop` into `master`, now both are on the same state. Hope I didn't break something else 😅

**Comment by Omranic** [comment]
This should be working now, so I'll close it but feel free to re-open if you still have any issues..
