### ISSUE TITLE
Slug should be snake_case even it's manually provided

### ISSUE THREAD

**Issue by IsraelOrtuno** [rinvex/laravel-attributes#51]
As of now, the `slug` is automatically generated in an _snake_case_ style only when it gets generated using the _Sluggable_ package (no slug provided when creating the attribute).

When we create an attribute providing a `slug`, it won't get formatted as _snake_case_.

**Reproduce**

```php
app('rinvex.attributes.attribute')->create([
    'slug' => 'foo-bar',
    'type'     => 'integer',
    'name'     => 'Count',
    'entities' => ['App\User'],
])
```

This will produce a `foo-bar` slug rather than `foo_bar`.

**Comment by Omranic** [comment]
Good point, I’ll add slug mutator to always enforce underscores..
