### ISSUE TITLE
Default Type Registration and Migrations

### ISSUE THREAD

**Issue by dhildreth** [rinvex/laravel-attributes#62]
Looking at https://github.com/rinvex/attributes/commit/622dfdd2ae8c5a56a45a66612f9e0175f7388df1#diff-ea0d11a7ac5ac10f344772d0863e113d, I'm wondering that if this is considered implementation details, why force the migration of these default types as well?  It'd be nice to somehow give the developer an option of opting out of the core type migrations.  Would it be better to provide an artisan command to publish (or copy) the core type migration files to the project's database/migration folder instead of loading from the AttributesServiceProvider?

Perhaps we move the core type migration files to the directory _.../database/core-type-migrations_.  This way, the following line of code will only load the necessary tables:
```
         // Load migrations
         ! $this->app->runningInConsole() || $this->loadMigrationsFrom(__DIR__.'/../../database/migrations');
```

Then, if the user wants to implement the default core types, they could run `php artisan vendor:publish` or `php artisan rinvex:publish:attributes`.

**Comment by Omranic** [comment]
You can now override migrations!
All packages have been updated to include this feature, check latest releases 😉 enjoy!
