### ISSUE TITLE
Deleting Attributes?

### ISSUE THREAD

**Issue by dhildreth** [rinvex/laravel-attributes#65]
I'm struggling with building a UI for creating, editing, and deleting attributes.  Specifically, I'm stuck on deleting the attributes from the entity (product).

I imagine it should be something as simple as a foreach loop to remove/unset all attributes:
```
    function syncAttributes(Product $product, ProductRequest $request)
   {
        foreach($product->getEntityAttributes() as $key => $value) {
            $product->{$key} = null;
        }
        $product->save();
```

However, that doesn't work and I'm left with this monstrosity of a solution:
```
        foreach($product->getEntityAttributes() as $key => $value) {
            $product->{$key} = null;
            $product->save();
            Cache::flush();
            $product = Product::find($product->id);
        }
```

I'm hoping this is one of those moments where I'm just missing something simple.  I could use a hand please!

**Comment by heydluv** [comment]
Have you tried doing `$attribute->delete();` as shown [here on line 240](https://github.com/rinvex/cortex-attributes/blob/ce8a3422393f8f4e70df7b177a8e172b3e18e589/src/Http/Controllers/Adminarea/AttributesController.php#L240)?

**Comment by dhildreth** [comment]
Thanks for the response, but that will actually delete the attribute entirely.  I still want to keep the attribute for the entity, but I want to 'null' it out.
