### ISSUE TITLE
Support for 5.7? 

### ISSUE THREAD

**Issue by jessetmia** [rinvex/laravel-attributes#68]
I recently found out about this repo as it fits a need we have with a system we are building. However, we are on 5.7, and while I've started to fork everything to test it, I can't see that being the resolution long term. I was wondering how often do you guys update when laravel releases a new version?

Thanks,

Jesse

**Comment by Omranic** [comment]
We try to keep te `develop` branch always up to date.

This package is now supports Laravel v5.7 so will close this issue.
