### ISSUE TITLE
Call to a member function add() on null

### ISSUE THREAD

**Issue by batFormat** [rinvex/laravel-attributes#69]
I have created attribute "conditions", and attach values.

$advert = \App\Models\Advert::find(400);
$advert->conditions->add(['value1', 'value2']);

Call to a member function add() on null

**Comment by Xesher** [comment]
+1

**Comment by batFormat** [comment]
I created an attribute that I try to add multiple values ​​to, and I can not.
I don't understand.

Do I need to add some method to the model?

**Comment by ikirabjob** [comment]
+1

**Comment by batFormat** [comment]
Please close.
The error was due to the fact that in the database I did not specify the attribute `is_collection`, with value `1`.
