### ISSUE TITLE
PostgreSQL error

### ISSUE THREAD

**Issue by rez1dent3** [rinvex/laravel-attributes#73]
I'm trying to use your library with pgsql. No luck so far!
```
   Illuminate\Database\QueryException  : SQLSTATE[42883]: Undefined function: 7 ERROR:  operator does not exist: text ->> unknown
LINE 1: ...tes" where 0 = 1 order by "sort_order" asc, "name"->>'$en' a...
                                                             ^
HINT:  No operator matches the given name and argument type(s). You might need to add explicit type casts. (SQL: select * from "attributes" where 0 = 1 order by "sort_order" asc, "name"->>'$en' asc)
```

**Comment by VladimirFrunza** [comment]
I have the same problem, also I have problems with MariaDB. As mentioned in another issue. I hope in closest future someone will fix this issue, cause I can not wait to use this awesome laravel-attributes repository :)

**Comment by rez1dent3** [comment]
@VladimirFrunza upgrade mariadb to 10.2 or install mysql/percona 5.7

**Comment by VladimirFrunza** [comment]
@rez1dent3 I have Mariadb v10.2.14

**Comment by VladimirFrunza** [comment]
I installed Mysql 5.7 and it works :) But anyway that is uncomfortable

**Comment by rez1dent3** [comment]
@VladimirFrunza I made a pull request #75 , make edits on mariadb.
I do not have a server with mariadb at the moment

**Comment by IsraelOrtuno** [comment]
> tired of waiting, made a pull request

That's the way to go! 😉👍

**Comment by rez1dent3** [comment]
@IsraelOrtuno The idea is to add a condition to sqlite. Since this database will not work.

**Comment by Omranic** [comment]
#75 merged! Sorry for the long delay.
