### ISSUE TITLE
Not working with laravel 5.5

### ISSUE THREAD

**Issue by johnsonthedev** [rinvex/laravel-attributes#74]
HI Omranic,

 I found the laravel-attributes package and feel this has great potential. Thank you very much for your effort building it ! I found out that the current version doesn't support Laravel 5.5. You mentioned because it is still in development release and you want to support latest laravel version. However 5.5 is the LTS release and using an older commit doesn't feel good considering the fact that the latest bug fixes are not included.

I am wondering if you have any roadmap for supporting 5.5 ?

In addition to that I tried to install earlier commit 0.0.3 for testing purposes but it requires rinvex/cacheable[dev-develop]  which also works only with 5.7

I tried to manipulate my composer.json with below entries, but it doesn't work because it requires the cacheable dev-release.

Any ideas on how to install it on Laravel 5.5 ? 

Thanks, Johnson

```
"rinvex/cacheable": "0.0.2",
"rinvex/laravel-attributes": "0.0.3"
```

**Comment by Omranic** [comment]
Thank you for the feedback.
Currently this package has been tagged as stable, and it's supporting Laravel v5.7+, there's no plans to support older versions at this moment. You can still fork the package and update composer.json to fit your needs.
