### ISSUE TITLE
Too few arguments to function Rinvex/Attributes/Models/Attribute::values()

### ISSUE THREAD

**Issue by uphlewis** [rinvex/laravel-attributes#79]
Hi! Great package, thanks.

Stumbled onto the above error when trying to lazy load `$attribute->values`

Would there be any drawbacks of changing the method signature of `Rinvex/Attributes/Models/Attribute::values()` slightly?

Currently the method looks like this:
```php
    /**
     * Get the entities attached to this attribute.
     *
     * @param string $value
     *
     * @return \Illuminate\Database\Eloquent\Relations\HasMany
     */
    public function values(string $value): HasMany
    {
        return $this->hasMany($value, 'attribute_id', 'id');
    }
```

So trying to access `$attribute->values` as a dynamic property throws an error because `Attribute::values()` expects a `$value` argument.

My proposed fix:
```php
    /**
     * Get the entities attached to this attribute.
     *
     * @param string|null [$valueModel]
     *
     * @return \Illuminate\Database\Eloquent\Relations\HasMany
     */
    public function values(string $valueModel = null): HasMany
    {
        if (!$valueModel && array_has($this->attributes, 'type')) {
            $valueModel = self::getTypeModel($this->attributes['type']);
        }

        return $this->hasMany($valueModel, 'attribute_id', 'id');
    }
```

Thoughts ?

**Comment by uphlewis** [comment]
This still doesn't solve the eager loading (`Attribute::with('values')`) issue, but it does solve the lazy loading issue.

**Comment by Omranic** [comment]
Thank you for your patience, I did a complete rewrite for the whole package and changed how collections & relationshs work. In the new refactor, it actually uses normal relationships, and should be easy and straightforward like default Laravel relationships. Although, that refactor is incomplete.

I'm still not happy with the overall performance (I believe we can reduce number of executed queries), if you want to check it out, see https://github.com/rinvex/laravel-attributes/tree/refactor-to-native-laravel-relationships

Currently no plans to merge that rewrite, but hopefully sometime I can get it to a stable state, improve performance and release it. Any help with that branch would be much appreciated! 🙂
