### ISSUE TITLE
setAttribute has not been applied, because there are collisions with other trait methods 

### ISSUE THREAD

**Issue by cord** [rinvex/laravel-attributes#80]
am trying to use this nice package within nova in combination Spatie\Translatable.

However combining both traits in the model 

```
class myModel extends Model {

    use \Rinvex\Attributes\Traits\Attributable;
    use \Spatie\Translatable\HasTranslations;

}
```

causes the error

**Trait method setAttribute has not been applied, because there are collisions with other trait methods**

Is there any way to work around this situation?

**Comment by cord** [comment]
Found this on stackoverflow: [Collisions with other trait methods](https://stackoverflow.com/questions/25064470/collisions-with-other-trait-methods)

and with some trial & error the following code seems to work

```
use Rinvex\Attributes\Traits\Attributable as Attributable;
use Rinvex\Support\Traits\HasTranslations as HasTranslations;

class myModel extends Model {
    use Attributable, HasTranslations {
        HasTranslations::setAttribute insteadof Attributable;
    }
}
```
can you confirm this would be a valid solution?

**Comment by hcyildirim** [comment]
@cord how did you solve this? I can't make it work.

**Comment by cord** [comment]
The solution above works here?

**Comment by hcyildirim** [comment]
> The solution above works here?

It does not work for me I guess. Im getting an error that says “id does not exists” when using both translatable and laravel-attributes.

**Comment by cord** [comment]
Sounds like a different issue to me?

**Comment by Omranic** [comment]
I confirm the above solution by @cord, that should work for trait collision.
