### ISSUE TITLE
Products have many attributes (Color, Size ...)

### ISSUE THREAD

**Issue by vanthao03596** [rinvex/laravel-attributes#83]
The product "My Product" has additional properties such as "Color", "Size", for example: Red + Size: L => Price 5000, Black + Size: L = > price 6000 ... I'm not sure how to save it and its operation, you can help me for example on adding new products with multiple attributes, each with different pricing attributes.

**Comment by thanhnhoncntt** [comment]
I think you use the product variation. Production variation link attributte and 
price by product variation

**Comment by Omranic** [comment]
The pricing features are out of this package's scope. This package only handle additional custom attributes, which is in your case the color & size. Checkout the docs for more info: https://github.com/rinvex/laravel-attributes#introduction
