### ISSUE TITLE
Installation fails - conflict with spatie/laravel-translatable versions

### ISSUE THREAD

**Issue by SunnyDayGuide** [rinvex/laravel-attributes#86]
Installation fails with Laravel 5.8 and spatie/laravel-translatable ^4.0

This package install is still requiring 3.1.0

- Can only install one of: spatie/laravel-translatable[v3.x-dev, 4.1.1].
    - Can only install one of: spatie/laravel-translatable[v3.x-dev, 4.1.1].
    - Can only install one of: spatie/laravel-translatable[v3.x-dev, 4.1.1].
    - rinvex/laravel-attributes v2.0.0 requires spatie/laravel-translatable ^3.1.0 -> satisfiable by spatie/laravel-translatable[v3.x-dev].
    - Installation request for rinvex/laravel-attributes ^2.0 -> satisfiable by rinvex/laravel-attributes[v2.0.0].
    - Installation request for spatie/laravel-translatable (locked at 4.1.1, required as ^4.1) -> satisfiable by spatie/laravel-translatable[4.1.1].

**Comment by nguyentranchung** [comment]
same problem when i installed spatie/laravel-tags
