### ISSUE TITLE
Call to undefined method Rinvex\Attributes\Models\Type\Varchar::isEmpty()

### ISSUE THREAD

**Issue by webaction** [rinvex/laravel-attributes#90]
I get this error when I deleted a record from the system.

I can see that it is triggered from the EntityWasDeleted Event.

**Comment by Omranic** [comment]
Honestly I didn't understand your question, but if you still need any help feel free to re-open this issue, and add more information so we can help.

**Comment by javoscript** [comment]
I'm getting the same error when trying to delete a non-collection value.
The method `isEmpty()` is being called on an instance of a value type (`Rinvex\Attributes\Models\Type\Varchar`, for example), instead of on a collection

**Comment by kimtrien** [comment]
Same error!

**Comment by javoscript** [comment]
I fixed it in my local project, and submitted a PR that was never merged...
Just in case it is useful to you: 
https://github.com/rinvex/laravel-attributes/pull/103/commits/8c0ec12c06014d4d8caaff9d082d8f5f116a0fac

**Comment by Omranic** [comment]
Thank you for your patience, this is now fixed in the merged PR #103
