### ISSUE TITLE
Base table or view not found: 1146 Table

### ISSUE THREAD

**Issue by mateng1210** [rinvex/laravel-attributes#93]
![image](https://user-images.githubusercontent.com/24752917/61506953-69a60080-aa16-11e9-9a48-b59ebf69a739.png)
![image](https://user-images.githubusercontent.com/24752917/61506969-7b87a380-aa16-11e9-8c30-bfd2f5066322.png)

mysql table data
![image](https://user-images.githubusercontent.com/24752917/61507002-a114ad00-aa16-11e9-9fbd-a3e1632921ad.png)

$product = Product::find(1);
QueryException：
![image](https://user-images.githubusercontent.com/24752917/61507047-cd302e00-aa16-11e9-93f2-ca75f96ee681.png)

**Comment by Omranic** [comment]
Honestly I didn't understand your question, but if you still need any help feel free to re-open this issue, and add more information so we can help.

**Comment by vahidalvandi** [comment]
so i have ..
