### ISSUE TITLE
How should i deal with cache if i have so much attribute in single model

### ISSUE THREAD

**Issue by azisyus** [rinvex/laravel-attributes#95]
Basically i have 40 attribute in single model and i cant use CacheableEloquent trait because that serialization process consumes all of my memory, my theory is $entityAttributeRelations variable is so big and there is not enough memory to serialize all of these objects.

**Comment by Omranic** [comment]
Thank you for the valuable feedback, and sorry for the delayed reply!

Upon further discussions about caching, we dropped caching from the core packages for more flexibility, and to leave it's responsibility for the application layer. Check recent commit https://github.com/rinvex/laravel-attributes/commit/2f3dbe2b5ebfa1c0a6adb48fcd962a82367eb9a1
